import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Head from "next/head";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <Head>
        <title>Cloud Club BINGO</title>
        <meta
          name='viewport'
          content='minimum-scale=1.0, initial-scale=1.0, width=device-width, shrink-to-fit=no, user-scalable=no, viewport-fit=cover'
        />
        <meta name='robots' content='index,nofollow' />
        <meta name='title' content='Cloud Club BINGO' />
        <meta name='description' content='사람을 찾아라! 빙고게임' />
        <meta property='og:type' content='website' />
        <meta name='og:title' content='Cloud Club BINGO' />
        <meta name='og:description' content='사람을 찾아라! 빙고게임' />
        <meta name='og:image' content='/images/title.png' />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
